<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\**" />
    <EmbeddedResource Remove="Data\Migrations\**" />
    <None Remove="Data\Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.17" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eVote360Pro.Application\eVote360Pro.Application.csproj" />
    <ProjectReference Include="..\eVote360Pro.Domain\eVote360Pro.Domain.csproj" />
    <ProjectReference Include="..\eVote360Pro.Shared\eVote360Pro.Shared.csproj" />
  </ItemGroup>

</Project>
