<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eVote360Pro.Application\eVote360Pro.Application.csproj" />
    <ProjectReference Include="..\eVote360Pro.Domain\eVote360Pro.Domain.csproj" />
    <ProjectReference Include="..\eVote360Pro.Infrastructure\eVote360Pro.Infrastructure.csproj" />
    <ProjectReference Include="..\eVote360Pro.Shared\eVote360Pro.Shared.csproj" />
  </ItemGroup>
</Project>